import { ATLAS_REVISION } from "./index";
import { EXECUTABLE_REVIEWS } from "./executable-review";
import { SCENE_COMPATIBILITY_REVIEWS } from "./scene-review";
import { PHYSICS_GAP_GROUPS, PHYSICS_GAP_REVIEWS } from "./physics-gaps";
import frozen from "./atlas-lab-reconciliation.v1.json";

export function reconciliationReviewReport(): string {
  return [
    "# R2–R5 — Additive Atlas reconciliation",
    "",
    `Canonical source: \`${ATLAS_REVISION}\`. R1's complete inventory is retained in [ATLAS_RECONCILIATION_R1.md](ATLAS_RECONCILIATION_R1.md).`,
    "",
    "No existing lab, source definition, binding, engine, host control or scene vocabulary is removed. These milestones complete the review and freeze; they do not claim implementation of unbound physics. Source programs are evidence, not execution permission.",
    "",
    "D1 amendment: tables and digests below represent the current additive inventory, including the accepted static 1D oscillator. The historical R5 baseline at 4159d2e is preserved in packages/atlas/fixtures/reconciliation-r5.v1.json. Original protocol branches/definitions are fingerprint-tested against that baseline; new oscillator enum/variants require updated strict consumers. No existing scene schema changed.",
    "",
    "## R2 — Executable mapping review (implemented)",
    "",
    "All 68 entries have an explicit disposition. The nine original bindings remain unchanged; D1 adds one accepted oscillator binding through the existing atlasBinding switch. Two restricted adapter candidates remain disabled pending unit/parameter acceptance. Every new model must extend existing contracts and worker supervision, not create a parallel executor.",
    "",
    "| Atlas ID | Disposition | Enabled existing binding | Next requirement |",
    "| --- | --- | --- | --- |",
    ...EXECUTABLE_REVIEWS.map(
      (r) =>
        `| \`${r.atlasId}\` | ${r.disposition} | ${r.enabled ? "yes" : "no"} | ${r.nextRequirement} |`,
    ),
    "",
    "### Preserved scientific conversions",
    "",
    ...EXECUTABLE_REVIEWS.filter((r) => r.scientificMapping).flatMap((r) => [
      `#### ${r.atlasId}`,
      "",
      r.scientificMapping!.conversion,
      "",
      r.scientificMapping!.basis,
      "",
      r.scientificMapping!.boundedScope,
      "",
      `Evidence: ${r.scientificMapping!.evidence.map((p) => `\`${p}\``).join(", ")}.`,
      "",
    ]),
    "Source review: pinned examples/python/qutip/adapters/dispersive_jc.py and tavis_cummings.py. Their rotating-frame/tensor conventions above are not silently substituted for Lab's existing closed cavity convention.",
    "",
    "## R3 — C2–C8 to existing quantum-scene/v1 (implemented)",
    "",
    "Seven ideas reviewed against the real QVIS vocabulary. Compatible scope does not imply a new model solver or automatic import of the B/C request envelopes. The additive grid-order utility converts only supplied bounded regular data; it does not resample, infer wavefunctions, normalize or modify existing adapters.",
    "",
    ...SCENE_COMPATIBILITY_REVIEWS.flatMap((r) => [
      `### ${r.id} — ${r.title}`,
      "",
      `Pinned source: [${r.sourceDocument}](https://github.com/expert10000/theory/blob/${ATLAS_REVISION}/docs/theory-lab/${r.sourceDocument}).`,
      "",
      `Existing vocabulary: ${r.vocabulary.join(", ")}. Modules: ${r.existingModules.map((p) => `\`${p}\``).join(", ")}.`,
      "",
      `Compatible scope: ${r.compatibleScope}`,
      "",
      `Conversion: ${r.requiredConversion}`,
      "",
      `Additive gap: ${r.remainingGap}`,
      "",
      `Evidence: ${r.evidence.map((p) => `\`${p}\``).join(", ")}.`,
      "",
    ]),
    "Keep QuantumResult → QuantumScene → independent consumers. Reuse current TS/Python validators, hashes, 16 MiB regular-scene budget, four fields and 3..49 grid axes; larger/chunked data retains the separate existing stream contract. No direct Lab-to-Math3D worker calls.",
    "",
    "## R4 — Genuine physics/model gaps (implemented review)",
    "",
    `Every Atlas ID is classified exactly once: ${PHYSICS_GAP_REVIEWS.filter(r=>r.status==="covered-subspace").length} covered subspaces, ${PHYSICS_GAP_REVIEWS.filter(r=>r.status==="parameter-adapter").length} parameter-adapter candidates and ${PHYSICS_GAP_REVIEWS.filter(r=>r.status==="new-model").length} entries requiring new model scope. Covered subspace never means the full Atlas Hamiltonian family is implemented. Priority 1 is adapter review; 2 is bounded first extensions; 3 is more involved physics; 4 is substantial many-body/QEC scope. This is an additive backlog, not authorization to execute or build every entry.`,
    "",
    "| Atlas ID | Gap status | Group | Priority |",
    "| --- | --- | --- | --- |",
    ...PHYSICS_GAP_REVIEWS.map(
      (r) =>
        `| \`${r.atlasId}\` | ${r.status} | ${r.groupId ?? "—"} | ${r.priority || "preserve"} |`,
    ),
    "",
    ...PHYSICS_GAP_GROUPS.flatMap((g) => [
      `### ${g.id} — ${g.title} (priority ${g.priority})`,
      "",
      `Entries: ${g.atlasIds.map((id) => `\`${id}\``).join(", ")}. Dependencies: ${g.dependencies.join(", ") || "none"}.`,
      "",
      `Reuse: ${g.reuse}`,
      ...(g.deliveredSubspaces?.length ? ["",`Delivered bounded subspaces: ${g.deliveredSubspaces.join("; ")}.`] : []),
      "",
      `Missing: ${g.missing}`,
      "",
      "Acceptance requirements:",
      "",
      ...g.acceptance.map((a) => `- ${a}`),
      "",
    ]),
    "D1 now delivers the bounded standalone static 1D oscillator within G02; the group retains all broader oscillator-family requirements. G01 restricted adapter candidates, Rice–Mele and XY/Heisenberg are further bounded candidates, not implemented here. The reconciliation review itself did not implement D1; the separate D1 commits do. All current labs remain available.",
    "",
    "## R5 — Reconciled Atlas ↔ Lab metadata freeze (implemented)",
    "",
    "The additive atlas-lab-reconciliation/v1 metadata contract is frozen in packages/atlas/atlas-lab-reconciliation.v1.json with a strict JSON Schema, semantic validator and deterministic regeneration check. It covers all 68 IDs, source examples, related-only models, nine preserved binding defaults/conventions, desktop/web/gateway/scene coverage, executable dispositions, C2–C8 review IDs and physics gap groups.",
    "",
    `Catalog digest: \`${frozen.catalogSha256}\`. Review/inventory digest: \`${frozen.reviewSha256}\`. Digests detect drift, not publisher identity or scientific truth.`,
    "",
    "### Current protocol digests; legacy branches retained",
    "",
    "Hashes below use SHA-256 of JSON.stringify(JSON.parse(schema)), avoiding platform line-ending differences. No existing job/result/scene schema was edited by R2–R5.",
    "",
    "| Existing schema | Semantic SHA-256 |",
    "| --- | --- |",
    ...frozen.protectedSchemas.map((s) => `| ${s.path} | \`${s.sha256}\` |`),
    "",
    "### Additive change policy",
    "",
    "- Keep all existing IDs, labs, bindings, operations, engines, host controls and scene formats. New mappings require explicit scientific conversions, bounded contracts and independent numerical acceptance.",
    "- Execution remains in existing atlasBinding + host/worker validation and runtime capabilities. This metadata, a source path, a related model or a geometry fixture cannot authorize execution.",
    "- Extend existing typed model modules/contracts and QVIS adapters. No B job/result workspace or C free-form bridge protocol is adopted; Math3D remains a separate consumer track.",
    "- Regenerate metadata/report only after reviewing changed definitions and evidence. Do not silently broaden scientific scope or weaken validation/budgets to make a new model fit.",
    "- Backward-compatible new optional fields or enum cases still require updated strict consumers and compatibility fixtures. A breaking semantic change requires a new contract version and migration; the metadata version does not version or replace quantum-job/result/scene protocols.",
    "- R5 freezes the reconciliation baseline, not the whole application. Future extensions stay possible and are recorded with additive tests; no existing capability is reduced.",
    "",
    "### Reproduce acceptance",
    "",
    "```powershell",
    "node scripts/sync-atlas.mjs --check",
    "npx tsx scripts/report-atlas.ts --check",
    "npx tsx scripts/freeze-atlas.ts --check",
    "npx tsx scripts/report-reconciliation.ts --check",
    "npm run typecheck",
    "npm test",
    "npm run test:worker",
    "npm run test:desktop",
    "npm run test:web",
    "npm run test:scenes",
    "```",
    "",
    "R2–R5 implementation means the mapping review, compatibility review, gap review and metadata freeze are delivered. It does not mean 59 additional Atlas entries, chemistry, periodic crystals or Math3D are implemented. All original feature paths and tests are retained.",
    "",
  ].join("\n");
}
