import { contextBridge, ipcRenderer } from "electron";
import type { QuantumBridge } from "../../../packages/contracts";
const bridge: QuantumBridge = {
  run: (job) => ipcRenderer.invoke("quantum:run", job),
  evolve: (job) => ipcRenderer.invoke("quantum:evolve", job),
  cavity: (job) => ipcRenderer.invoke("quantum:cavity", job),
  orbital: (job) => ipcRenderer.invoke("quantum:orbital", job),
  lindblad: (job) => ipcRenderer.invoke("quantum:lindblad", job),
  sweep: (job) => ipcRenderer.invoke("quantum:sweep", job),
  manyBody: (job) => ipcRenderer.invoke("quantum:many-body", job),
  circuit: (job) => ipcRenderer.invoke("quantum:circuit", job),
  oscillator: (job) => ipcRenderer.invoke("quantum:oscillator", job),
  oscillatorEvolve: (job) => ipcRenderer.invoke("quantum:oscillator-evolve", job),
  oscillatorDrive: (job) => ipcRenderer.invoke("quantum:oscillator-drive", job),
  oscillatorPulse: (job) => ipcRenderer.invoke("quantum:oscillator-pulse", job),
  oscillatorDamped: (job) => ipcRenderer.invoke("quantum:oscillator-damped", job),
  oscillatorParametric: (job) => ipcRenderer.invoke("quantum:oscillator-parametric", job),
  oscillatorAnharmonic: (job) => ipcRenderer.invoke("quantum:oscillator-anharmonic", job),
  topology: (job) => ipcRenderer.invoke("quantum:topology", job),
  openAtlasSource: (id) => ipcRenderer.invoke("quantum:open-atlas-source", id),
  cancel: (jobId) => ipcRenderer.invoke("quantum:cancel", jobId),
  readData: (jobId) => ipcRenderer.invoke("quantum:read-data", jobId),
  onProgress: (listener) => {
    const handler = (_event: Electron.IpcRendererEvent, value: unknown) =>
      listener(value as Parameters<typeof listener>[0]);
    ipcRenderer.on("quantum:progress", handler);
    return () => ipcRenderer.removeListener("quantum:progress", handler);
  },
  getStatus: () => ipcRenderer.invoke("quantum:status"),
  getCapabilities: () => ipcRenderer.invoke("quantum:capabilities"),
  getResources: () => ipcRenderer.invoke("quantum:resources"),
  restart: () => ipcRenderer.invoke("quantum:restart"),
  saveWorkspace: (snapshot) => ipcRenderer.invoke("quantum:save-workspace", snapshot),
  loadWorkspace: () => ipcRenderer.invoke("quantum:load-workspace"),
  listRuns: () => ipcRenderer.invoke("quantum:list-runs"),
  getVerifiedRun: (runId) => ipcRenderer.invoke("quantum:verified-run",runId),
  inspectSavedRun: (runId) => ipcRenderer.invoke("quantum:inspect-saved-run",runId),
  rerunSaved: (runId,fingerprint) => ipcRenderer.invoke("quantum:rerun-saved",runId,fingerprint),
  getRunComparisonPins: () => ipcRenderer.invoke("quantum:comparison-pins"),
  setRunComparisonPins: (pins) => ipcRenderer.invoke("quantum:set-comparison-pins",pins),
  getSpectrumRun: (runId) => ipcRenderer.invoke("quantum:spectrum-run", runId),
  getRabiRun: (runId) => ipcRenderer.invoke("quantum:rabi-run", runId),
  getEvolutionRun: (runId) => ipcRenderer.invoke("quantum:evolution-run", runId),
  getCavityRun: (runId) => ipcRenderer.invoke("quantum:cavity-run", runId),
  getLindbladRun: (runId) => ipcRenderer.invoke("quantum:lindblad-run", runId),
  getCircuitRun: (runId) => ipcRenderer.invoke("quantum:circuit-run", runId),
  getManyBodyRun: (runId) => ipcRenderer.invoke("quantum:many-body-run", runId),
  getSweepRun: (runId) => ipcRenderer.invoke("quantum:sweep-run", runId),
  getTopologyRun: (runId) => ipcRenderer.invoke("quantum:topology-run", runId),
  getOrbitalRun: (runId) => ipcRenderer.invoke("quantum:orbital-run", runId),
  getOscillatorRun: (runId) => ipcRenderer.invoke("quantum:oscillator-run", runId),
  saveSpectrumStudy: (result) => ipcRenderer.invoke("quantum:save-spectrum-study", result),
  getSpectrumStudy: (studyId) => ipcRenderer.invoke("quantum:get-spectrum-study", studyId),
  listSpectrumStudies: () => ipcRenderer.invoke("quantum:list-spectrum-studies"),
  getScene: (runId, view) => ipcRenderer.invoke("quantum:scene", runId, view),
  exportScene: (runId, view, format) => ipcRenderer.invoke("quantum:export-scene", runId, view, format),
  importSceneStream: () => ipcRenderer.invoke("quantum:import-scene-stream"),
  readSceneChunk: (id,path) => ipcRenderer.invoke("quantum:scene-chunk",id,path),
  releaseSceneStream: id => ipcRenderer.invoke("quantum:release-scene-stream",id),
  importScene: () => ipcRenderer.invoke("quantum:import-scene"),
  getSceneExample: (request) => ipcRenderer.invoke("quantum:scene-example", request),
  exportSceneExample: (request) => ipcRenderer.invoke("quantum:export-scene-example", request),
  exportRun: (runId, format) => ipcRenderer.invoke("quantum:export-run", runId, format),
  exportRunBundle: (runId) => ipcRenderer.invoke("quantum:export-run-bundle",runId),
  importRunBundle: () => ipcRenderer.invoke("quantum:import-run-bundle"),
};
contextBridge.exposeInMainWorld("quantum", Object.freeze(bridge));
